Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,11 +16,19 @@ while true; do
     sleep 3
 done
 
+# Switch repository if the default one fails
+termux-change-repo
+
 # Clean and install all required dependencies
 echo "Installing termux packages"
 apt-get clean
-apt-get update >/dev/null
-apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null
+apt-get update || {
+    echo "Failed to update, switching mirror with termux-change-repo"
+    termux-change-repo
+    apt-get update
+}
+
+apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade
 pkg install x11-repo -y
 pkg install pulseaudio -y
 pkg install xwayland -y
@@ -49,8 +57,8 @@ fi
 INSTALL_WOW64=0
 
 echo "Select an option"
-echo "1) Install previous emuinabox with box86"
-echo "2) Install new emuinabox wow64 version"
+echo "1) Install previous mobox with box86"
+echo "2) Install new mobox wow64 version"
 echo ""
 echo -n "Selected number: "
 read i
@@ -66,12 +74,12 @@ case "$i" in
 ;;
 esac
 
-echo "Installing emuinabox"
+echo "Installing mobox"
 
-echo "Updating package manager"
-
+# Create the following directory(It doesn't exist since we'd removed glibc earlier)
 mkdir -p $PREFIX/glibc/opt/package-manager/installed
 
+# Depending on what we selected earlier, set the private token and project id
 if [ "$INSTALL_WOW64" = "1" ]; then
     echo "PRIVATE_TOKEN=glpat-h5r7HjKoPKZPxmfg79xs
     PROJECT_ID=54240888">$PREFIX/glibc/opt/package-manager/token
@@ -80,25 +88,30 @@ else
     PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
 fi
 
+# Loads up our private token and project id into our current shell session
 . $PREFIX/glibc/opt/package-manager/token
 
-# Use your repo's package manager
-curl -L https://raw.githubusercontent.com/YashSoPro/emuinabox_packages/main/package-manager -o "$PREFIX/glibc/opt/package-manager/package-manager"
+# Downloads the package-manager script
 
+if [ "$INSTALL_WOW64" = "1" ]; then
+    curl https://raw.githubusercontent.com/YashSoPro/mobox/main/package-manager -o "$PREFIX/glibc/opt/package-manager/package-manager"
+else
+    curl https://raw.githubusercontent.com/YashSoPro/mobox/main/package-manager -o "$PREFIX/glibc/opt/package-manager/package-manager"
+fi
+
+# Executes the package manager script which sets up everything mobox related
 . $PREFIX/glibc/opt/package-manager/package-manager
 
+# This is what installs everything mobox needs(base packages and wine)
 sync-all
 
+# Installs wine
 if [ "$INSTALL_WOW64" = "1" ]; then
     sync-package wine-9.3-vanilla-wow64
 else
     sync-package wine-ge-custom-8-25
 fi
 
-# Create a symlink for emuinabox
-if [ -f "$PREFIX/glibc/opt/scripts/mobox" ]; then
-    ln -sf "$PREFIX/glibc/opt/scripts/mobox" "$PREFIX/bin/emuinabox"
-    echo "To start - type \"emuinabox\""
-else
-    echo "Error: emuinabox script not found. Check the installation."
-fi
+# Create a symlink for mobox
+ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/emuinabox
+echo "To start - type \"emuinabox\""
