Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -121,4 +121,101 @@ fi
 
 # Create a symlink for mobox
 ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/emuinabox
-echo "To start - type \"emuinabox\""
+echo "To start - type \"emuinabox\""#!/bin/bash
+
+echo "Installing termux-am..."
+pkg install termux-am -y
+
+termux-setup-storage & sleep 4
+
+while true; do
+    if [ -d ~/storage/shared ]; then
+        break
+    else
+        echo "Storage permission denied. Please grant access."
+    fi
+    sleep 3
+done
+
+# Clean and install all required dependencies
+echo "Installing termux packages..."
+apt-get clean
+apt-get update >/dev/null
+apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null
+pkg install x11-repo pulseaudio xwayland wget tsu root-repo patchelf p7zip xorg-xrandr ncurses-utils hashdeep termux-x11-nightly -y
+
+# Remove previous glibc
+if [ -e $PREFIX/glibc ]; then
+    echo -n "Removing previous glibc. Continue? (Y/n) "
+    read i
+    if [[ "$i" == "Y" || "$i" == "y" ]]; then
+        rm -rf $PREFIX/glibc
+    fi
+fi
+
+# Select installation option
+INSTALL_WOW64=0
+
+echo "Select an option:"
+echo "1) Install previous emuinabox with box86"
+echo "2) Install new emuinabox wow64 version"
+echo -n "Selected number: "
+read i
+case "$i" in
+1)
+    INSTALL_WOW64=0
+;;
+2)
+    INSTALL_WOW64=1
+;;
+*)
+    echo "Invalid option selected."
+    exit 1
+;;
+esac
+
+# Create directories if not exist
+mkdir -p $PREFIX/glibc/opt/package-manager
+mkdir -p $PREFIX/glibc/opt/scripts/mobox
+
+# Download mobox if not present
+if [ ! -d "$PREFIX/glibc/opt/scripts/mobox" ]; then
+    echo "Downloading mobox..."
+    git clone https://github.com/YashSoPro/emuinabox.git $PREFIX/glibc/opt/scripts/mobox
+fi
+
+# Create token file
+if [ "$INSTALL_WOW64" -eq 1 ]; then
+    echo "PRIVATE_TOKEN=glpat-h5r7HjKoPKZPxmfg79xs
+PROJECT_ID=54240888" > $PREFIX/glibc/opt/package-manager/token
+else
+    echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
+PROJECT_ID=52465323" > $PREFIX/glibc/opt/package-manager/token
+fi
+
+# Load token and project ID
+. $PREFIX/glibc/opt/package-manager/token
+
+# Download the package manager script
+echo "Downloading package manager..."
+curl -s -o "$PREFIX/glibc/opt/package-manager/package-manager" https://raw.githubusercontent.com/YashSoPro/emuinabox/main/package-manager
+
+# Make scripts executable
+chmod +x $PREFIX/glibc/opt/scripts/mobox/*
+
+# Execute the package manager script
+. $PREFIX/glibc/opt/package-manager/package-manager
+
+# Sync and install necessary packages
+sync-all
+
+# Install wine based on user selection
+if [ "$INSTALL_WOW64" -eq 1 ]; then
+    sync-package wine-9.3-vanilla-wow64
+else
+    sync-package wine-ge-custom-8-25
+fi
+
+# Create a symlink for emuinabox
+ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/emuinabox
+echo "Setup complete. To start, type 'emuinabox'."
